# Generated by Django 5.0.4 on 2024-04-07 11:38

import django.db.models.deletion
import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_no', models.CharField(blank=True, default=report.models.report_number, max_length=500, null=True)),
                ('nature_of_report', models.CharField(choices=[('Smuggling', 'Smuggling'), ('Fraud', 'Fraud'), ('Extortion', 'Extortion'), ('Bribery', 'Bribery'), ('Corruption', 'Corruption'), ('Misappropriation', 'Misappropriation'), ('Other', 'Other'), ('Nepotism', 'Nepotism'), ('Procurement Fraud', 'Procurement Fraud'), ('Racism', 'Racism'), ('Theft', 'Theft'), ('Sexual Harassment', 'Sexual Harassment'), ('Criminal', 'Criminal'), ('Unethical', 'Unethical'), ('Other', 'Other')], default=0, max_length=20)),
                ('station', models.CharField(choices=[('Harare', 'Harare'), ('Victoria Falls', 'Victoria Falls'), ('Bulawayo', 'Bulawayo'), ('Kariba', 'Kariba'), ('Other', 'Other')], default=0, max_length=20)),
                ('other_station', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField()),
                ('location_of_incident', models.CharField(max_length=100)),
                ('name_of_party_involved', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_detail', models.TextField(max_length=3000)),
                ('upload_evidence', models.FileField(blank=True, null=True, upload_to='tipoff_media/')),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Position_Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_no', models.CharField(blank=True, max_length=100, null=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, default='wiDe01D', max_length=11, null=True, unique=True)),
                ('report_status', models.CharField(choices=[('Evaluation', 'Evaluation'), ('Investigation', 'Investigation'), ('Disciplinary ', 'Disciplinary'), ('Insufficient', 'Insufficient Evidence'), ('Closed', 'Closed')], max_length=20, null=True)),
                ('additional_details', models.TextField(blank=True, max_length=3000, null=True)),
                ('report_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.incidentreport')),
            ],
        ),
    ]
