# Generated by Django 5.0.4 on 2024-06-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='other_station',
            new_name='other_location',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='OPwlIWTJJ', max_length=11, null=True, unique=True),
        ),
    ]
