# Generated by Django 5.0.4 on 2025-04-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_other_station_incidentreport_other_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='name_of_party_involved',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='1Vg8PPNiv', max_length=11, null=True, unique=True),
        ),
    ]
