# Generated by Django 5.0.4 on 2025-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_incidentreport_name_of_party_involved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='role',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(blank=True, default='Gedc9', max_length=11, null=True, unique=True),
        ),
    ]
